
name: Snyk Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
  
permissions:
  contents: read
  security-events: write
  
jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk SAST Scan
        run: snyk code test --sarif > snyk.sarif
        continue-on-error: true

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif

      - name: Adding the sarif result to Snyk GUI
        run: snyk monitor
